#!/bin/bash
set -e

usermod -d $APPDIR www-data
mkdir -p $APPDIR/.ssh/
if [ -e /etc/persistent-conf/ssh/id_rsa ]; then
	cp -f /etc/persistent-conf/ssh/id_rsa $APPDIR/.ssh/id_rsa
	chmod 600 $APPDIR/.ssh/id_rsa
fi
if [ -e /etc/persistent-conf/ssh/known_hosts ]; then
	cp -f /etc/persistent-conf/ssh/known_hosts $APPDIR/.ssh/known_hosts
fi
chown -R www-data:www-data $APPDIR/.ssh
chmod 700 $APPDIR/.ssh

chown www-data:www-data $APPDIR/storage


_init()  {
    # At this point we add the runtime thumbor configuration to
    # the thumbor.conf config file.
    #
    # If the container is started multiple times, append our init
    # modifications to a fresh copy of the original config file.
    if [ ! -f /etc/thumbor.conf.original ]; then
        cp /etc/thumbor.conf /etc/thumbor.conf.original
    else
        cp /etc/thumbor.conf.original /etc/thumbor.conf
    fi


    if [ -S /dev/log ]; then
        cat /setup/config/thumbor-syslog.conf >> /etc/thumbor.conf
    fi

    if [ -f /etc/persistent-conf/thumbor.conf ]; then
        cat /etc/persistent-conf/thumbor.conf >> /etc/thumbor.conf
    fi

    echo -e "\n$CONFIG\n" >> /etc/thumbor.conf

    if [ -n "$SECURITY_KEY" ]; then
        echo -e "\nSECURITY_KEY=\"$SECURITY_KEY\"\nALLOW_UNSAFE_URL=False\n" >> /etc/thumbor.conf
    fi
}


_start() {
    echo "Starting thumbor..."

    sudo -u www-data -H \
        PYTHON_EGG_CACHE=/srv/thumbor/.egg-cache \
        "$(which thumbor)"
}


_help () {
    echo "Available options:"
    echo " start          - Starts the thumbor server (default)"
    echo " help           - Displays this help"
    echo " [command]      - Execute a the specified shell command."
}



_init


if [ -z "$1" ]; then
    _start
else
    case "$1" in
        start)
            _start
            ;;
        help)
            _help
            ;;
        *)
            if [ -x $1 ]; then
                $1
            else
                prog=$(which $1)
                if [ -n "${prog}" ] ; then
                    shift 1
                    $prog $@
                else
                    echo "Not found: $1"
                    exit 1
                fi
            fi
            ;;
    esac
fi
