#!/bin/bash
#
#

set -e

_install() {
    local pkg=$1 ver=$2 afterhook=$3

    cd /tmp

    # Download the snapshot
    wget -q https://github.com/thumbor/$pkg/archive/${ver}.zip && \
        unzip ${ver}.zip >/dev/null && rm -f ${ver}.zip

    cd "$pkg-${ver}"

    if [ -e /setup/patches/"${pkg}" ]; then
        for p in /setup/patches/"${pkg}"/*.patch; do
            patch -p1 < "${p}"
        done
    fi

    if [ -e "requirements" ]; then
        apt-get install \
            --no-install-recommends --ignore-missing --fix-broken -y \
                $(cat requirements | grep -v "^\(libpngwriter\|libfaac\|libtiffxx0c2\|libavcodec53\|libavformat53\|gstreamer0.10-ffmpeg\|libtiff4\|redis-server\)")
    fi

    python setup.py install

    pip install "raven<5"

    if [ -n "$afterhook" ]; then
        $afterhook
    fi

    cd /
    rm -rf "/tmp/$pkg-${ver}"
}

_install_thumbor() {
    cp -f debian/thumbor.conf /etc/thumbor.conf
}

_install thumbor $THUMBOR_VERSION _install_thumbor

if [ "${THUMBOR_ENGINE}" = "opencv" ]; then
    _install opencv-engine $OPENCV_ENGINE_VERSION
elif [ "${THUMBOR_ENGINE}" = "graphicsmagick" ]; then
    _install graphicsmagick-engine $GRAPHICSMAGICK_ENGINE_VERSION
else
    echo "ERROR: Unsupported thumbor engine: ${THUMBOR_ENGINE}" >&2
    exit 1
fi
